server:
  port: 8080
  servlet:
    session:
      tracking-modes: COOKIE
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  main:
    banner-mode: CONSOLE
  datasource:
    url: jdbc:mysql://localhost:3306/fooddb
    username: chef
    password: oporayam
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: on
